export enum RouteNames {
  AUTH_STACK = "AUTH_STACK",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
  AUTHORIZE_STACK = "AUTHORIZE_STACK",
  HOME_SCREEN = "HOME_SCREEN",
  MAKE_PAYMENT_SCREEN = "MAKE_PAYMENT_SCREEN",
  UPLOAD_BALANCE_SCREEN = "UPLOAD_BALANCE_SCREEN",
  SPENDING_SCREEN = "SPENDING_SCREEN",
}
